# Generated by Django 5.2.6 on 2025-09-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="data",
            new_name="date",
        ),
    ]
