# Generated by Django 5.2.6 on 2025-10-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_options_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=500,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("paid", "Оплачено"),
                    ("failed", "Неудача"),
                    ("canceled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии Stripe",
                max_length=255,
                null=True,
                verbose_name="ID сессии Stripe",
            ),
        ),
    ]
