# Generated by Django 5.2.6 on 2025-10-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_stripe_payment_intent_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("stripe", "Stripe")],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
