# Generated by Django 5.2.6 on 2025-09-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название курса", max_length=100, verbose_name="Название курса"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание курса", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью курса",
                        null=True,
                        upload_to="materials/course_preview_image/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lessons",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название урока", max_length=100, verbose_name="Название урока"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание урока", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью урока",
                        null=True,
                        upload_to="materials/lesson_preview_image/",
                    ),
                ),
                (
                    "url_video",
                    models.CharField(
                        help_text="Укажите ссылку на видео урока", max_length=100, verbose_name="Ссылка на видео урока"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите к какому курсу относится урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="Курс урока",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["name"],
            },
        ),
    ]
