# Generated by Django 5.2.6 on 2025-09-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lessons",
            new_name="Lesson",
        ),
    ]
