# Generated by Django 5.2.6 on 2025-10-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите стоимость курса в рублях",
                max_digits=10,
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите стоимость урока в рублях",
                max_digits=10,
                verbose_name="Стоимость урока",
            ),
        ),
    ]
