# Generated by Django 5.2.6 on 2025-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Автоматически обновляется при изменении курса или его уроков",
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
