name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install flake8

    - name: Run linter
      run: flake8 . --count --max-complexity=10 --statistics

  test:
    runs-on: ubuntu-latest
    needs: lint

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ secrets.TEST_NAME_DB }}
          POSTGRES_USER: ${{ secrets.TEST_USER_DB }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_PASSWORD_DB }}
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

    - name: Run migrations
      env:
        DEBUG: "True"
        SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
        NAME_DB: ${{ secrets.TEST_NAME_DB }}
        USER_DB: ${{ secrets.TEST_USER_DB }}
        PASSWORD_DB: ${{ secrets.TEST_PASSWORD_DB }}
        HOST: "localhost"
        PORT: "5432"
        REDIS_HOST: "localhost"
        REDIS_PORT: "6379"
      run: python manage.py migrate --noinput

    - name: Run tests
      env:
        DEBUG: "True"
        SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
        NAME_DB: ${{ secrets.TEST_NAME_DB }}
        USER_DB: ${{ secrets.TEST_USER_DB }}
        PASSWORD_DB: ${{ secrets.TEST_PASSWORD_DB }}
        HOST: "localhost"
        PORT: "5432"
        REDIS_HOST: "localhost"
        REDIS_PORT: "6379"
      run: python manage.py test --noinput

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t education-platform:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "Starting deployment..."

          cd /opt/education-platform

          git pull origin main

          docker-compose -f docker-compose.prod.yaml down
          docker-compose -f docker-compose.prod.yaml up -d --build

          echo "Deployment completed!"